name: Build & Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          brew install cmake@3.25.3 ninja@1.11.1 |
          brew install opencv@4.7.0 |
          brew install sdl2 sdl2_ttf@2.20.2 sdl2_image@2.6.3 sdl2_mixer@2.6.3

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=$(brew --prefix)/bin/ninja -G Ninja -S . -B build

      - name: Link
        run: ninja
        working-directory: build

      - name: Test
        run: ctest
        working-directory: build
